image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: cd marxbank; mvn compile

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
  - port: 3000

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
